version: '1.0'
services:
  app:
    build: ./db
    depends_on:
      db: 
        condition: service_healthy
    links:
      - db
  db:
    build: ./db
    ports: 
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
  python:
    build: ./app
    ports:
      - 4000:4000
    depends_on:
      db: 
        condition: service_healthy